function formatTime(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleString([], {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

function riskLabel(score) {
  if (score >= 70) return { label: "HIGH", cls: "text-red-400" };
  if (score >= 30) return { label: "MEDIUM", cls: "text-amber-400" };
  return { label: "LOW", cls: "text-green-400" };
}

export default function ExplanationCard({ anomaly, onClose }) {
  if (!anomaly) return null;

  const risk = riskLabel(anomaly.risk_score);

  return (
    <div className="bg-slate-900 border border-cyan-500/25 rounded-xl p-5 shadow-lg shadow-cyan-500/5">
      {/* Header */}
      <div className="flex items-start justify-between mb-4">
        <div>
          <div className="flex items-center gap-2 mb-0.5">
            <div className="w-2 h-2 rounded-full bg-cyan-500 shrink-0" />
            <h2 className="text-sm font-semibold text-slate-100">
              AI Security Explanation
            </h2>
          </div>
          <p className="text-[10px] text-slate-500 pl-4">
            Generated by the SentinelX RAG explainability engine (Phase 6)
          </p>
        </div>
        <button
          onClick={onClose}
          className="text-slate-600 hover:text-slate-300 text-xl leading-none ml-4 shrink-0 transition-colors"
          aria-label="Close"
        >
          ×
        </button>
      </div>

      {/* Event metadata */}
      <div className="bg-slate-950 rounded-lg border border-slate-800 p-3.5 mb-4 font-mono text-[11px]">
        <div className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-slate-400">
          <span className="text-slate-600">User</span>
          <span className="text-slate-200">{anomaly.user_email}</span>

          <span className="text-slate-600">Endpoint</span>
          <span className="text-slate-200 break-all">{anomaly.endpoint}</span>

          <span className="text-slate-600">Method</span>
          <span className="text-slate-200">{anomaly.method}</span>

          <span className="text-slate-600">Risk Score</span>
          <span className={`font-bold ${risk.cls}`}>
            {anomaly.risk_score}/100{" "}
            <span className="text-[10px] font-normal opacity-70">
              ({risk.label})
            </span>
          </span>

          <span className="text-slate-600">IP Address</span>
          <span className="text-slate-200">{anomaly.ip_address || "—"}</span>

          <span className="text-slate-600">Timestamp</span>
          <span className="text-slate-200">{formatTime(anomaly.created_at)}</span>
        </div>
      </div>

      {/* RAG explanation */}
      <div className="bg-cyan-500/5 border border-cyan-500/20 rounded-lg p-4">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[9px] text-cyan-500 uppercase tracking-widest font-semibold">
            RAG Explanation
          </span>
          <div className="flex-1 h-px bg-cyan-500/10" />
        </div>
        {anomaly.ai_explanation ? (
          <p className="text-sm text-slate-300 leading-relaxed">
            {anomaly.ai_explanation}
          </p>
        ) : (
          <p className="text-xs text-slate-600 italic">
            No explanation yet — explanations are generated asynchronously after
            anomaly detection. Reload in a few seconds.
          </p>
        )}
      </div>
    </div>
  );
}
